spring:
  application:
    name: hello-spring
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url:  jdbc:h2:mem:hello-spring
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
